// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// compute_BGe_posterior
double compute_BGe_posterior(DataFrame df, unsigned alpha_w, NumericVector nu, double alpha_mu);
RcppExport SEXP _bfcs_compute_BGe_posterior(SEXP dfSEXP, SEXP alpha_wSEXP, SEXP nuSEXP, SEXP alpha_muSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< unsigned >::type alpha_w(alpha_wSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_mu(alpha_muSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_BGe_posterior(df, alpha_w, nu, alpha_mu));
    return rcpp_result_gen;
END_RCPP
}
// compute_BGe_score
double compute_BGe_score(double N, const arma::vec& means, const arma::mat& covmat, List parents, unsigned alpha_w, const arma::vec& nu_vec, double alpha_mu);
RcppExport SEXP _bfcs_compute_BGe_score(SEXP NSEXP, SEXP meansSEXP, SEXP covmatSEXP, SEXP parentsSEXP, SEXP alpha_wSEXP, SEXP nu_vecSEXP, SEXP alpha_muSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type N(NSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type means(meansSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type covmat(covmatSEXP);
    Rcpp::traits::input_parameter< List >::type parents(parentsSEXP);
    Rcpp::traits::input_parameter< unsigned >::type alpha_w(alpha_wSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type nu_vec(nu_vecSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_mu(alpha_muSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_BGe_score(N, means, covmat, parents, alpha_w, nu_vec, alpha_mu));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bfcs_compute_BGe_posterior", (DL_FUNC) &_bfcs_compute_BGe_posterior, 4},
    {"_bfcs_compute_BGe_score", (DL_FUNC) &_bfcs_compute_BGe_score, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_bfcs(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
