# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_BGe_posterior <- function(df, alpha_w, nu, alpha_mu = 1.0) {
    .Call(`_bfcs_compute_BGe_posterior`, df, alpha_w, nu, alpha_mu)
}

compute_BGe_score <- function(N, means, covmat, parents, alpha_w, nu_vec, alpha_mu = 1.0) {
    .Call(`_bfcs_compute_BGe_score`, N, means, covmat, parents, alpha_w, nu_vec, alpha_mu)
}

