# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute Bayesian Gaussian equivalent (BGe) score for a given Bayesian network
#' on given sufficient statistics from data.
#' 
#' @details For a better understanding of how the BGe score is obtained see the article 
#' [Geiger and Heckerman (2002)](https://projecteuclid.org/euclid.aos/1035844981)
#' as well as the discussion in [Kuipers et al. (2014)](https://projecteuclid.org/euclid.aos/1407420013).
#'
#' @param N Integer number of observations.
#' @param means Numeric vector containing variable means.
#' @param covmat Numeric covariance matrix.
#' @param parents List of parents for each node to describe Bayesian network.
#' @param alpha_w Numeric parameter of the covariance's Wishart prior (scale matrix).
#' @param nu_vec Numeric parameter of the covariance's Wishart prior (degrees of freedom)
#' @param alpha_mu Numeric parameter of the mean's Gaussian prior (expected value).
#'
#' @return Bayesian Gaussian equivalent (BGe) score for given data on the
#' given Bayesian network.
compute_BGe_score <- function(N, means, covmat, parents, alpha_w, nu_vec, alpha_mu = 1.0) {
    .Call(`_BFCS_compute_BGe_score`, N, means, covmat, parents, alpha_w, nu_vec, alpha_mu)
}

